function createfigure(ymatrix1)
%CREATEFIGURE(ymatrix1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 17-Dec-2022 14:31:58

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
set(bar1(5),'DisplayName','CNN-CF');
set(bar1(4),'DisplayName','KNN-CF');
set(bar1(3),'DisplayName','SVM-CF');
set(bar1(2),'DisplayName','NB-CF');
set(bar1(1),'DisplayName','NN-CF');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[1 2 3 4],'XTickLabel',...
    {'Accuracy','Recall','Precision','F-measure'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','bestoutside');

